#!/bin/sh
set -eu

usage() {
  cat <<'EOF'
Usage: ./install.sh [--force] [--headless]

Installs this repo into the expected config locations:
  ~/.config/aerospace/aerospace.toml from shared config plus host routes
  ~/.config/aerospace/pull-app.sh -> aerospace/pull-app.sh
  ~/.config/ghostty/config.ghostty -> ghostty/config.ghostty, when Ghostty is installed
  ~/.config/tmux/tmux.conf -> tmux/tmux.conf
  ~/.config/nvim           -> nvim
  ~/.config/zsh/.zshrc     -> zsh/.zshrc
  ~/.config/zsh/.zshenv    -> zsh/.zshenv
  ~/.zshenv                -> ~/.config/zsh/.zshenv
  ~/.codex/config.toml     from shared, profile, and machine layers
  ~/.codex/AGENTS.md       from shared Codex instructions
  ~/.local/bin/codex-sync -> codex/managed/codex-sync

It also creates ~/.zshrc.local and appends a source line for the shared zsh
config to ~/.zshrc.

Set DOTFILES_INSTALL_GHOSTTY=1 to force Ghostty config installation on machines
where Ghostty is not installed.

Use --headless to skip Ghostty config even when Ghostty is installed.

Use --force to move conflicting files/directories aside with a timestamped
.bak suffix before linking.
EOF
}

force=false
headless=false
while [ "$#" -gt 0 ]; do
  case "$1" in
    --force)
      force=true
      ;;
    --headless)
      headless=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 2
      ;;
  esac
  shift
done

repo_dir=$(CDPATH= cd "$(dirname "$0")" && pwd -P)
backup_suffix=".bak.$(date +%Y%m%d%H%M%S)"
tmux_plugin_dir="$HOME/.config/tmux/plugins"
tpm_dir="$tmux_plugin_dir/tpm"

info() {
  printf '%s\n' "$*"
}

ensure_parent() {
  mkdir -p "$(dirname "$1")"
}

backup_existing() {
  path=$1

  if [ "$force" = true ]; then
    info "Backing up $path -> $path$backup_suffix"
    mv "$path" "$path$backup_suffix"
  else
    printf 'Refusing to overwrite %s. Re-run with --force to back it up first.\n' "$path" >&2
    exit 1
  fi
}

link_path() {
  src=$1
  dest=$2

  ensure_parent "$dest"

  if [ -L "$dest" ]; then
    current=$(readlink "$dest")
    if [ "$current" = "$src" ]; then
      info "Already linked: $dest -> $src"
      return
    fi
    rm "$dest"
  elif [ -e "$dest" ]; then
    backup_existing "$dest"
  fi

  ln -s "$src" "$dest"
  info "Linked: $dest -> $src"
}

append_once() {
  line=$1
  file=$2
  heading=$3

  touch "$file"
  if grep -Fqx "$line" "$file"; then
    info "Already configured: $file"
    return
  fi

  {
    printf '\n%s\n' "$heading"
    printf '%s\n' "$line"
  } >> "$file"
  info "Updated: $file"
}

mkdir -p "$HOME/.config/aerospace" "$HOME/.config/tmux" "$HOME/.config/zsh" "$tmux_plugin_dir"

"$repo_dir/aerospace/render-config.sh"
link_path "$repo_dir/aerospace/pull-app.sh" "$HOME/.config/aerospace/pull-app.sh"

if [ "$headless" = true ] && [ "${DOTFILES_INSTALL_GHOSTTY:-}" != 1 ]; then
  info "Skipping Ghostty config in headless mode"
elif [ "${DOTFILES_INSTALL_GHOSTTY:-}" = 1 ] || command -v ghostty >/dev/null 2>&1; then
  mkdir -p "$HOME/.config/ghostty"
  link_path "$repo_dir/ghostty/config.ghostty" "$HOME/.config/ghostty/config.ghostty"
else
  info "Skipping Ghostty config; use --headless to make this explicit or set DOTFILES_INSTALL_GHOSTTY=1 to force it"
fi

link_path "$repo_dir/tmux/tmux.conf" "$HOME/.config/tmux/tmux.conf"
link_path "$repo_dir/nvim" "$HOME/.config/nvim"
link_path "$repo_dir/zsh/.zshrc" "$HOME/.config/zsh/.zshrc"
link_path "$repo_dir/zsh/.zshenv" "$HOME/.config/zsh/.zshenv"
link_path "$HOME/.config/zsh/.zshenv" "$HOME/.zshenv"

touch "$HOME/.zshrc.local"
chmod 600 "$HOME/.zshrc.local"
append_once 'source "$HOME/.config/zsh/.zshrc"' "$HOME/.zshrc" '# Personal zsh customisations'

link_path "$repo_dir/codex/managed/codex-sync" "$HOME/.local/bin/codex-sync"

if command -v codex >/dev/null 2>&1; then
  unmanaged_codex=false
  if [ -f "$HOME/.codex/config.toml" ] && \
    ! grep -Eq '# Generated by codex/managed/(manage|codex-sync)' "$HOME/.codex/config.toml"; then
    unmanaged_codex=true
  fi
  if [ -f "$HOME/.codex/AGENTS.md" ] && \
    ! grep -Fq '# Shared Codex instructions' "$HOME/.codex/AGENTS.md"; then
    unmanaged_codex=true
  fi
  if [ "$unmanaged_codex" = true ] && [ "$force" != true ]; then
    info "Skipping unmanaged Codex config or instructions; re-run with --force to back them up and replace them"
  else
    "$repo_dir/codex/managed/codex-sync" apply
  fi
else
  info "Skipping Codex configuration; install Codex first"
fi

if [ ! -d "$tpm_dir" ]; then
  if command -v git >/dev/null 2>&1; then
    git clone https://github.com/tmux-plugins/tpm "$tpm_dir"
  else
    info "git not found; install TPM manually at $tpm_dir"
  fi
else
  info "Already installed: $tpm_dir"
fi

if [ -x "$tpm_dir/bin/install_plugins" ]; then
  if command -v tmux >/dev/null 2>&1; then
    tmux start-server \; \
      set-environment -g TMUX_PLUGIN_MANAGER_PATH "$tmux_plugin_dir/" \; \
      source-file "$HOME/.config/tmux/tmux.conf"
    "$tpm_dir/bin/install_plugins"
  else
    info "tmux not found; install tmux, then run $tpm_dir/bin/install_plugins"
  fi
fi

info
info "Done. Tmux plugins are installed when tmux is available."
