[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.microsoft.Excel'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.microsoft.Word'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.microsoft.Powerpoint'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.microsoft.onenote.mac'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.microsoft.OneDrive'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.microsoft.CompanyPortalMac'
run = 'move-node-to-workspace 4'
